name: Docker Image CI

on:
  push:
    tags:
    - '*'
    branches:
    - '*'

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to GHCR
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ secrets.GH_USERNAME }}
        password: ${{ secrets.GH_TOKEN }}
    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)
    - name: Build and push netpolviz image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: build/docker/Dockerfile
        push: true
        tags: ghcr.io/arivum/netpolviz/netpolviz:${{ steps.get_version.outputs.VERSION }},ghcr.io/arivum/netpolviz/netpolviz:latest
    - name: Build and push operator
      uses: docker/build-push-action@v2
      with:
        context: .
        file: build/docker/Dockerfile
        push: true
        tags: ghcr.io/arivum/netpolviz/netpolviz-operator:${{ steps.get_version.outputs.VERSION }},ghcr.io/arivum/netpolviz/netpolviz-operator:latest
